# Generated by Django 3.0.8 on 2020-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200803_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_c',
            field=models.CharField(max_length=160),
        ),
    ]
